apiVersion: v1
kind: Service
metadata:
  name: django-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: django
    version: {{ .Values.service.activeVersion }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}