apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  domains:
    - {{ .Values.ingress.host }}